apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-api
  name: location-svc-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30003
  selector:
    service: location-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-api
  name: location-deployment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-api
  template:
    metadata:
      labels:
        service: location-api
    spec:
      containers:
      - image: ar251/udaconnect:location.api.v1
        name: location-container-api
        imagePullPolicy: Always
        env:
        - name: KAFKA_API
          valueFrom:
            secretKeyRef:
              name: kafka-env
              key: KAFKA_API
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TOPIC
      restartPolicy: Always